# ?????? ??: postgresql ??? sqlserver
db.type=postgresql

# PostgreSQL
postgresql.driver=org.postgresql.Driver
postgresql.url=jdbc:postgresql://localhost:5432/pharmacy_db
postgresql.user=postgres
postgresql.password=0000


sqlserver.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
sqlserver.url=jdbc:sqlserver://localhost:1434;databaseName=Pharmacy;encrypt=true;trustServerCertificate=true;
sqlserver.user=sa
sqlserver.password=0000